name: PluralKitMC
version: 0.4.9
author: Allymonies
main: com.omnipico.pluralkitmc.PluralKitMC
api-version: 1.16
website: omnipico.com
softdepend: [Vault, DiscordSRV]
commands:
  pk:
    description: Base command for PluralKitMC
    usage: /pk <help>
    permission: pluralkitmc.pk
permissions:
  pluralkitmc.pk:
    default: true
    description: Allows usage of /pk
  pluralkitmc.update:
    default: true
    description: Allows manually updating one's system, bypassing the cache
  pluralkitmc.link:
    default: true
    description: Allows linking one's pluralkit token to Minecraft (bypassing privacy settings)
  pluralkitmc.reload:
    default: false
    description: Allows reloading the PluralKitMC config
  pluralkitmc.*:
    default: op
    description: Allows access to every pluralkitmc command.
    children:
      pluralkitmc.pk: true
      pluralkitmc.update: true
      pluralkitmc.link: true
      pluralkitmc.reload: true
